### ISSUE TITLE
clangd 11: jump to definition can fail

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1002]
I'm trying to jump to a function referenced in a comment

```
porcupine.plugins.langserver ERROR: (PID=17908) error while handling langserver event
Traceback (most recent call last):
  File "/home/akuli/porcupine-venv/lib/python3.9/site-packages/porcupine/plugins/langserver.py", line 424, in _run_stuff_once
    self._handle_lsp_event(lsp_event)
  File "/home/akuli/porcupine-venv/lib/python3.9/site-packages/porcupine/plugins/langserver.py", line 587, in _handle_lsp_event
    [
  File "/home/akuli/porcupine-venv/lib/python3.9/site-packages/porcupine/plugins/langserver.py", line 587, in <listcomp>
    [
  File "/home/akuli/porcupine-venv/lib/python3.9/site-packages/porcupine/plugins/langserver.py", line 269, in _get_jump_paths_and_ranges
    yield (utils.file_url_to_path(location.uri), location.range)
  File "/home/akuli/porcupine-venv/lib/python3.9/site-packages/porcupine/utils.py", line 121, in file_url_to_path
    assert file_url.startswith("file://")
AssertionError
```

**Comment by Akuli** [comment]
Can't reproduce. Will reopen if I can get it to happen again.
