### ISSUE TITLE
click import error when running "black" test

### ISSUE THREAD

**Issue by ihammadasghar** [Akuli/porcupine#1047]
When I ran `black porcupine/plugins/filemanager.py`, it gave me this:
```Traceback (most recent call last):
  File "C:\Users\ihamm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ihamm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Hammad\porcupine\env\Scripts\black.exe\__main__.py", line 7, in <module>
  File "D:\Hammad\porcupine\env\lib\site-packages\black\__init__.py", line 1065, in patched_main
    patch_click()
  File "D:\Hammad\porcupine\env\lib\site-packages\black\__init__.py", line 1052, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (D:\Hammad\porcupine\env\lib\site-packages\click\__init__.py)```

**Comment by ihammadasghar** [comment]
It worked fine after I upgraded black to the latest version.

**Comment by Akuli** [comment]
I updated black in #1046, and you now get the latest version if you do `pip install -r requirements-dev.txt`.
