### ISSUE TITLE
Error switching to "blue" ttk theme

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1055]
When I select "blue" from the "UI Themes" menu, I get:

```
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/akuli/porcu/porcupine/plugins/directory_tree.py", line 141, in _config_tags
    gray = utils.mix_colors(fg, bg, 0.5)
  File "/home/akuli/porcu/porcupine/utils.py", line 252, in mix_colors
    for value1, value2 in zip(widget.winfo_rgb(color1), widget.winfo_rgb(color2))
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1165, in winfo_rgb
    self.tk.call('winfo', 'rgb', self._w, color))
_tkinter.TclError: unknown color name ""
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/akuli/porcu/porcupine/plugins/git_status.py", line 174, in config_color_tags
    gray = utils.mix_colors(fg, bg, 0.5)
  File "/home/akuli/porcu/porcupine/utils.py", line 252, in mix_colors
    for value1, value2 in zip(widget.winfo_rgb(color1), widget.winfo_rgb(color2))
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1165, in winfo_rgb
    self.tk.call('winfo', 'rgb', self._w, color))
_tkinter.TclError: unknown color name ""
```

**Comment by rdbende** [comment]
Happens with a whole bunch of other themes too:

- elegance
- itft1
- keramik
- kroc
- plastik
- smog
- winxpblue
