### ISSUE TITLE
LangServer seems to do stuff after getting removed from langservers

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#113]
```
[2020-08-15 21:50:22,279] porcupine.plugins.langserver.2218 DEBUG: getting remov
ed from langservers
[2020-08-15 21:50:22,859] porcupine.plugins.langserver.2218 DEBUG: got 29856 byt
es of data
[2020-08-15 21:50:22,866] porcupine.plugins.langserver.2218 ERROR: error while h
andling langserver event
Traceback (most recent call last):
  File "/home/akuli/porcu/porcupine/plugins/langserver.py", line 377, in _run_st
uff_once
    self._handle_lsp_event(lsp_event)
  File "/home/akuli/porcu/porcupine/plugins/langserver.py", line 417, in _handle
_lsp_event
    f'{req.cursor_pos} linestart', req.cursor_pos)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3246, in get
    return self.tk.call(self._w, 'get', index1, index2)
_tkinter.TclError: invalid command name ".!tabmanager.!filetab3.!maintext_actual_widget"
```

**Comment by Akuli** [comment]
first line of that log file

```
[2020-08-15 20:37:21,498] porcupine._logs DEBUG: starting Porcupine 0.76.4-git-78d452e from '/home/akuli/porcu/porcupine'
```
