### ISSUE TITLE
error while langserver shuts down

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#127]
```
[2020-08-18 13:16:20,390] porcupine._logs DEBUG: starting Porcupine 0.77.0+git.ee0120d from '/home/akuli/porcu/porcupine'

...

[2020-08-18 16:21:45,004] porcupine.tabs INFO: applying filetype settings: {'filename_patterns': ['*.p
y'], 'shebang_regex': 'python(\\d(\\.\\d)?)?$', 'pygments_lexer': 'pygments.lexers.Python3Lexer', 'tab
s2spaces': True, 'indent_size': 4, 'max_line_length': 79, 'commands': {'run': '{python} {file}'}, 'aut
ocomplete_chars': ['.'], 'langserver': {'command': 'pyls', 'language_id': 'python'}}
[2020-08-18 16:21:45,005] porcupine.settings DEBUG: pygments_lexer was set to <class 'pygments.lexers.
python.PythonLexer'>, generating <<TabSettingChanged:pygments_lexer>> events
[2020-08-18 16:21:45,015] porcupine.plugins.editorconfig INFO: file opened: /home/akuli/porcu/porcupin
e/textwidget.py
[2020-08-18 16:21:45,015] porcupine.plugins.editorconfig DEBUG: applying settings to /home/akuli/porcu
/porcupine/textwidget.py
[2020-08-18 16:21:45,015] porcupine.plugins.editorconfig DEBUG: parsing /home/akuli/porcu/.editorconfi
g
[2020-08-18 16:21:45,016] porcupine.plugins.editorconfig INFO: setting tabs2spaces to True
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig INFO: setting indent_size to 4
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig DEBUG: encoding not specified in editorconfig
s
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig INFO: setting max_line_length to 100
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig DEBUG: line_ending not specified in editorcon
figs
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig DEBUG: trim_trailing_whitespace not specified
 in editorconfigs
[2020-08-18 16:21:45,017] porcupine.plugins.editorconfig INFO: setting insert_final_newline to True
[2020-08-18 16:21:45,069] porcupine.settings DEBUG: autocomplete_chars was set to ['.'], generating <<
TabSettingChanged:autocomplete_chars>> events
[2020-08-18 16:21:45,072] porcupine.settings DEBUG: langserver was set to LangSe
rverConfig(command='pyls', language_id='python', port=None), generating <<TabSettingChanged:langserver>> events
[2020-08-18 16:21:45,073] porcupine.plugins.langserver INFO: Switching langservers: None --> <LangServer: PID 2244, LangServerId(command='pyls', port=None, project_root=PosixPath('/home/akuli/porcu')), 3 tabs opened>
[2020-08-18 16:21:45,073] porcupine.plugins.langserver.2244 DEBUG: tab opened
[2020-08-18 16:21:45,080] porcupine.settings DEBUG: max_line_length was set to 100, generating <<TabSettingChanged:max_line_length>> events
[2020-08-18 16:21:45,082] porcupine.settings DEBUG: commands was set to CommandsConfig(compile='', run='{python} {file}', lint=''), generating <<TabSettingChanged:commands>> events
[2020-08-18 16:21:45,846] porcupine.plugins.langserver.2244 DEBUG: got 937 bytes of data
[2020-08-18 16:21:46,292] porcupine.plugins.langserver.2244 DEBUG: tab closed
[2020-08-18 16:21:46,661] porcupine.plugins.langserver.2244 DEBUG: got 405 bytes of data
[2020-08-18 16:21:46,662] porcupine.plugins.langserver.2244 ERROR: error while handling langserver event
Traceback (most recent call last):
  File "/home/akuli/porcu/porcupine/plugins/langserver.py", line 377, in _run_stuff_once
    self._handle_lsp_event(lsp_event)
  File "/home/akuli/porcu/porcupine/plugins/langserver.py", line 468, in _handle_lsp_event
    tab for tab in self.tabs_opened.keys()
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by Akuli** [comment]
the langserver isn't actually shutting down here, there's another tab that keeps it alive (otherwise logs would say `no more open tabs, shutting down`)
