### ISSUE TITLE
Trying to open porcupine after closing with tab of file later deleted crashes on Mac

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1270]
Log:
```Traceback
Moosems-MacBook-Pro:porcupine Moosems$ python3 -m porcupine
log file: /Users/Moosems/Library/Logs/Porcupine/2023-04-13T16-03-57.txt
porcupine.plugins.drop_to_open ERROR: dragging files to Porcupine won't work because tkdnd isn't installed
porcupine.tabs ERROR: opening '/Users/Moosems/Desktop/DIP-dev/test.spec' failed
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/porcupine/porcupine/tabs.py", line 692, in reload
    with self.path.open("r", encoding=self.settings.get("encoding", str)) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Moosems/Desktop/DIP-dev/test.spec'
objc[36459]: Invalid or prematurely-freed autorelease pool 0x7fc180ee9240.
Abort trap: 6
```

**Comment by Akuli** [comment]
You have the weirdest bugs...

**Comment by Moosems** [comment]
I know :).

**Comment by rdbende** [comment]
"most outlandish issues", as he said :D

**Comment by Moosems** [comment]
I have a joke with my friends these days and its as follows: in my phone case, I have a fortune cookie that says "Your co-workers take pleasure in your great sense of creativity" and, referring to you guys as my "co-workers" since I code more with you two than anyone else, I go "No they don't. I'm the bug finder. I find the most ridiculous bugs and they love and hate me for it" and then everyone has a good laugh cause all my friends are programmers.

**Comment by Akuli** [comment]
As a temporary workaround you can disable "Remember open tabs when Porcupine is closed and reopened" in settings.

**Comment by Moosems** [comment]
I recreated the file to close it in Porcupine to avoid the issue in the future but I think it would be nice to get this fixed in a more permanent manner to not crash if the file doesn't exist.

**Comment by rdbende** [comment]
> more permanent manner to not crash if the file doesn't exist.

It should show a messagebox like this:

![image](https://user-images.githubusercontent.com/77941087/231887445-d2fd2cf2-1752-416b-bb1c-4e03a4120eec.png)

**Comment by Akuli** [comment]
I think the bug happens when the message box is shown without the rest of Porcupine (there is a `.withdraw()`).

I hope the dialog will eventually go away, because it is annoying, and I don't like showing popups to the user in general. See #1158

**Comment by Moosems** [comment]
Put a message log in the status bar?

**Comment by Moosems** [comment]
@Akuli Why do you dislike popups?

**Comment by Akuli** [comment]
A popup distracts you from whatever it is you are trying to do. Usually I just want to just close the tab that corresponds with a deleted file, and having to first exit a popup just makes that about 5x slower.

**Comment by Moosems** [comment]
*Silently deletes the popup at opening of DIP.*
