### ISSUE TITLE
Scrolling while click dragging line numbers

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1272]
```traceback
porcupine.plugins.langserver ERROR: (PID=41804) error while handling langserver event
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/porcupine/porcupine/plugins/langserver.py", line 358, in _run_stuff_once
    self._handle_lsp_event(lsp_event)
  File "/Users/Moosems/Desktop/porcupine/porcupine/plugins/langserver.py", line 549, in _handle_lsp_event
    raise NotImplementedError(repr(lsp_event))
NotImplementedError: ResponseError(message_id=13, code=-32602, message='NotImplementedError: Python version 3.11 is currently not supported.', data={'traceback': ['  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume\n    self._handle_request(message[\'id\'], message[\'method\'], message.get(\'params\'))\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request\n    handler_result = handler(params)\n                     ^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler\n    return method(**(params or {}))\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/python_ls.py", line 331, in m_text_document__hover\n    return self.hover(textDocument[\'uri\'], position)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/python_ls.py", line 265, in hover\n    return self._hook(\'pyls_hover\', doc_uri, position=position) or {\'contents\': \'\'}\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/python_ls.py", line 156, in _hook\n    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 327, in traced_hookexec\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_result.py", line 33, in from_call\n    result = func()\n             ^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 324, in <lambda>\n    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/plugins/hover.py", line 13, in pyls_hover\n    definitions = document.jedi_script().infer(**code_position)\n                  ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/workspace.py", line 25, in wrapper\n    return method(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyls/workspace.py", line 279, in jedi_script\n    return jedi.Script(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jedi/api/__init__.py", line 184, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jedi/inference/__init__.py", line 91, in __init__\n    self.grammar = environment.get_grammar()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jedi/cache.py", line 111, in wrapper\n    result = method(self, *args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jedi/api/environment.py", line 37, in get_grammar\n    return parso.load_grammar(version=version_string)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/parso/grammar.py", line 260, in load_grammar\n    return load_grammar(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/parso/grammar.py", line 256, in load_grammar\n    raise NotImplementedError(message)\n']})
```

**Comment by rdbende** [comment]
This doesn't seem to be related to scrolling

**Comment by Moosems** [comment]
Only occured when scrolling in the text after clicking and holding down the mouse on the linenums, dragging down, dragging into the Text widget, and then scrolling the Text while still keeping down my mouse.

**Comment by Akuli** [comment]
>NotImplementedError: Python version 3.11 is currently not supported.

This error message really doesn't look like it has to do with scrolling. But it looks like Porcupine needs a better default langserver for Python files. It currently uses `pyls` which is outdated in other ways too.

Pyright's langserver is probably the best open-source option (it is a subset of Pylance, the default langserver in vscode). At some point me and PurpleMyst looked into using pyright, but we had some problem with it.

**Comment by Akuli** [comment]
Related: 560

**Comment by Akuli** [comment]
This issue has nothing to do with scrolling and there are already many other langserver issues.
