### ISSUE TITLE
Using "quit()" in porcupine debugger crashes app

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1285]
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/Moosems/Desktop/porcupine/porcupine/plugins/porcupine_debug_prompt.py", line 68, in on_enter_key
    self.show(f"\n{out.getvalue()}>>> ")
  File "/Users/Moosems/Desktop/porcupine/porcupine/plugins/porcupine_debug_prompt.py", line 51, in show
    self.textwidget.insert("end - 1 char", string)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 3809, in insert
    self.tk.call((self._w, 'insert', index, chars) + args)
_tkinter.TclError: invalid command name ".!panedwindow.!panedwindow.!tabmanager.!prompttab.!text"
```

**Comment by Akuli** [comment]
What would you expect `quit()` to do?

**Comment by Moosems** [comment]
Maybe close the debugger? The real idea was trying to access to a terminal XD
