### ISSUE TITLE
new python-language-server problem

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#180]
```
porcupine.plugins.langserver.5337 ERROR: error while receiving lsp events
Traceback (most recent call last):
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/langserver.py", line 376, in _run_stuff_once
    lsp_events = self._lsp_client.recv(received_bytes)
  File "/home/akuli/.local/lib/python3.7/site-packages/sansio_lsp_client/client.py", line 119, in recv
    messages = list(_parse_messages(self._recv_buf))
  File "/home/akuli/.local/lib/python3.7/site-packages/sansio_lsp_client/io_handler.py", line 189, in _parse_messages
    parsed = _parse_one_message(response_buf)
  File "/home/akuli/.local/lib/python3.7/site-packages/sansio_lsp_client/io_handler.py", line 123, in _parse_one_message
    assert set(headers.keys()) == {"content-type", "content-length"}
AssertionError
```

works: python-language-server==0.34.1

does not work: python-language-server==0.36.2

**Comment by Akuli** [comment]
I think it didn't work because i had old sansio-lsp-client, older than what's in requirements.txt
