### ISSUE TITLE
PYTHONPATH in exe-installer-installed porcupine

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#242]
I debugged a weird problem with arrinao. Here's what happens when Porcupine is installed using a windows exe installer:
1. A python gets installed with Porcupine, to `...\AppData\Local\Programs\Porcupine\...`. Its only purpose is to run Porcupine
2. pynsist sets PYTHONPATH environment variable when porcupine starts, so that the Porcupine python finds its modules
3. Arrinao writes `import tkinter` into a Python file and presses F5
4. Porcupine opens up a new command prompt, which inherits `PYTHONPATH` env var from Porcupine's python
5. Comand prompt runs Arrinao's python (not same as Porcupine's python), which inherits `PYTHONPATH` env var from command prompt 
6. Arrinao's python sees `PYTHONPATH` and tries to import Porcupine python's tkinter
7. Arrinao gets a weird error:

```
py minesweeper.py
Traceback (most recent call last):
  File "C:\Users\Martin\minesweeper\minesweeper.py", line 3, in <module>
    import tkinter
  File "C:\Users\Martin\AppData\Local\Programs\Porcupine\pkgs\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: DLL load failed while importing _tkinter: The specified module could not be found.

-----------------------------
The program failed with status 1.
Press Enter to close this window...
```

**Comment by Akuli** [comment]
Putting this to end of `_run_in_windows_cmd` in `plugins/run/terminal.py` fixes problem:

```
    new_env = dict(os.environ)
    del new_env['PYTHONPATH']
    subprocess.Popen(command, env=new_env)
```
