### ISSUE TITLE
project root detection with subREADMEs

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#362]
There is `more_plugins/README.md` which makes porcupine think that `more_plugins` is a project separate from porcupine.

**Comment by Akuli** [comment]
This also causes errors in directory tree, which assumes that if `git status` succeeds, then its output is relative to the detected project root:

```
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/directory_tree.py", line 293, in open_file_or_dir
    self.open_and_refresh_directory(self.get_path(selected_id), selected_id)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/directory_tree.py", line 234, in open_and_refresh_directory
    git_status = self.git_statuses[relevant_parents[-1]]
KeyError: PosixPath('/home/akuli/porcu')
```
