### ISSUE TITLE
sometimes tests freeze weirdly

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#379]
hard to reproduce, has happened on my system and in ci, ctrl+c traceback says something about threads (don't have the traceback anymore)

**Comment by Akuli** [comment]
Saw the traceback again today. It's `threading.py` internals waiting for non-daemon threads to complete, with no information about where those threads were started.

**Comment by Akuli** [comment]
Happened on github actions in #454 but no traceback from github actions cancel button

**Comment by Akuli** [comment]
Still happens. https://github.com/Akuli/porcupine/runs/2914972787?check_suite_focus=true

**Comment by Akuli** [comment]
And still happens: https://github.com/Akuli/porcupine/runs/3040353850

**Comment by Akuli** [comment]
On #734 I got this error from Ctrl+C after freeze I think it is new error:

```
======================= 179 passed, 4 skipped in 49.99s ========================
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

Note it says `concurrent/futures/thread.py`. This file has code that should tell thread pools to exit, but apparently gets stuck somehow.
