### ISSUE TITLE
tkinter focus_get() corner case

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#566]
```
aku@aku-work:~$ py -m porcupine
log file: /home/aku/.cache/porcupine/log/2021-07-06T11-03-25.txt
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/utils.py", line 490, in run_the_callback
    return callback(event)  # may return 'break'
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/autocomplete.py", line 306, in <lambda>
    lambda event: self.receive_completions(event.data_class(Response)),
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/autocomplete.py", line 360, in receive_completions
    if self._user_wants_to_see_popup():
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/autocomplete.py", line 347, in _user_wants_to_see_popup
    self._tab.focus_get() == self._tab.textwidget
  File "/usr/lib/python3.8/tkinter/__init__.py", line 758, in focus_get
    return self._nametowidget(name)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1507, in nametowidget
    w = w.children[n]
KeyError: '__tk_filedialog'
```

This error happens when the user wants auto-completions, but the currently focused widget was created in plain tcl, not in tkinter.

**Comment by Akuli** [comment]
Created https://bugs.python.org/issue44592
