### ISSUE TITLE
weird freezing with langserver

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#635]
Has never happened before. The whole Porcupine freezes, because apparently pyls doesn't read stdin. When I kill the pyls process, I see this in porcupine:

```
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 597, in run_stuff
    if self._run_stuff_once():
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 382, in _run_stuff_once
    self._io.write(self._lsp_client.send())
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 102, in write
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
porcupine.plugins.langserver ERROR: (PID=10398) langserver process terminated unexpectedly, was killed by signal 9 (SIGKILL)
```

If I interrupt the frozen Porcupine with Ctrl+C, I get a very similar traceback:

```
^Cporcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 597, in run_stuff
    if self._run_stuff_once():
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 382, in _run_stuff_once
    self._io.write(self._lsp_client.send())
  File "/home/aku/.local/lib/python3.8/site-packages/porcupine/plugins/langserver.py", line 102, in write
    self._process.stdin.flush()
KeyboardInterrupt
```

**Comment by Akuli** [comment]
Based on `sudo strace -p 12849`, where `12849` is the pid, the langserver is busy indexing my home folder. I was editing a script in `~/foo.py`.

**Comment by Akuli** [comment]
#640 fixes the freezing in Porcupine. It does nothing to prevent a weird langserver from walking through every path in the entire home folder, but that's not really Porcupine's fault. I will add checks like "if running this specific langserver with project root set to home folder" if it is still a problem.
