### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#73]
triggered in porcupine 0.72.0, don't know how i did it and whether it's possible to get this with latest porcupine

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/akuli/.local/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/akuli/.local/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/autocomplete.py", line 423, in _filter_through_completions
    assert self._orig_cursorpos is not None
AssertionError
```

**Comment by Akuli** [comment]
happened again

```
[2020-08-15 20:37:21,498] porcupine._logs DEBUG: starting Porcupine 0.76.4-git-78d452e from '/home/aku
li/porcu/porcupine'

...

[2020-08-15 22:39:42,792] porcupine.plugins.langserver INFO: Switching langservers: None --> <LangServ
er: PID 5142, LangServerId(command='pyls', port=None, project_root=PosixPath('/home/akuli/porcu')), 3 
tabs opened>
[2020-08-15 22:39:42,792] porcupine.plugins.langserver.5142 DEBUG: tab opened
[2020-08-15 22:39:42,798] porcupine.settings DEBUG: max_line_length was set to 100, generating <<TabSe
ttingChanged:max_line_length>> events
[2020-08-15 22:39:42,801] porcupine.settings DEBUG: commands was set to CommandsConfig(compile='', run
='{python} {file}', lint=''), generating <<TabSettingChanged:commands>> events
[2020-08-15 22:39:43,484] porcupine.plugins.langserver.5142 DEBUG: got 241 bytes of data
[2020-08-15 22:42:31,821] porcupine.plugins.langserver.5142 DEBUG: got 741 bytes of data
[2020-08-15 22:42:33,382] porcupine.plugins.langserver.5142 DEBUG: got 741 bytes of data
[2020-08-15 22:42:34,801] porcupine.plugins.langserver.5142 DEBUG: got 907 bytes of data
[2020-08-15 22:42:37,935] porcupine.plugins.langserver.5142 DEBUG: got 542 bytes of data
[2020-08-15 22:42:38,239] porcupine.plugins.langserver.5142 DEBUG: got 34595 bytes of data
[2020-08-15 22:42:38,335] porcupine._run ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/akuli/porcu/porcupine/plugins/autocomplete.py", line 461, in _filter_through_completions
    assert self._orig_cursorpos is not None
AssertionError
```

**Comment by Akuli** [comment]
This still keeps happening

**Comment by Akuli** [comment]
I now have a guess for how this might be happening:
1. `on_any_key()` runs, and the popup is still completing. To get the key inserted first and then filter the completions accordingly, it calls `after_idle(self._filter_through_completions)`.
2. Before the `after_idle` callback runs, completing stops (e.g. due to another `after_idle` callback) and `_orig_cursorpos` is set to `None`.
3. When `_filter_through_completions` finally runs, we are no completing and we get the error.

To see whether this is really what happens, I added an assert in d8dd0be. Also, #645 deletes `tab.after_idle(completer._reject)`, and that might fix this too.

**Comment by Akuli** [comment]
```
log file: /home/akuli/.cache/porcupine/log/2021-08-14T11-51-15.txt
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/utils.py", line 440, in run_the_callback
    return callback(event)  # may return 'break'
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/hover.py", line 68, in on_hover_response
    self._show_label(text)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/hover.py", line 42, in _show_label
    wrap=True,
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/textutils.py", line 774, in place_popup
    assert bbox is not None
AssertionError
```
