### ISSUE TITLE
pickle error

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#761]
```
porcupine._state ERROR: Error in tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/akuli/.local/lib/python3.7/site-packages/porcupine/plugins/restart.py", line 29, in save_states
    pickle.dump(file_contents, file)
AttributeError: Can't pickle local object 'TomlDecoder.get_empty_inline_table.<locals>.DynamicInlineTableDict'
```

To reproduce put this to filetypes.toml and try close cpp file

```ini
["C++"]
langserver = {command = "clangd", language_id = "cpp", settings = {clangd = {arguments = ["-std=c++17"]}}}
```

**Comment by Akuli** [comment]
apparently updating `toml` to `tomli` would help
